import type { Metadata } from "next";
import { Geist } from "next/font/google";

import AuroraGradient from "../components/auroraGradient/auroraGradientAnimated";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} antialiased`}>
        <AuroraGradient>{children}</AuroraGradient>
      </body>
    </html>
  );
}
